version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    # environment:
    #   MYSQL_ROOT_PASSWORD: example
    #   MYSQL_DATABASE: bx4tzgrjfpptbqjg7uyr
    #   MYSQL_USER: ucyug1o0s8d2gupy
    #   MYSQL_PASSWORD: Xd0MHrMMM8C2YqbvhNP2
